#!/usr/bin/env node
/**
 * Blue Rider DS — token build (zero dependencies)
 *
 * Compiles DTCG-format token source (src/tokens/source/*.tokens.json) into:
 *   dist/tokens.css      — CSS custom properties (:root = primitives + dark
 *                          semantics; [data-theme="light"] = light overrides)
 *   dist/tokens.js       — flat JS object (ESM) for JS consumers/tooling
 *   dist/tokens.d.ts     — TypeScript types
 *
 * Naming grammar: --br-{category}-{path…}, kebab-case, mirroring Figma
 * variable names 1:1 (e.g. Figma "Background/Action-Primary" →
 * --br-color-bg-action-primary).
 *
 * Run: node src/tokens/build.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const srcDir = join(root, 'source');
const distDir = join(root, 'dist');
mkdirSync(distDir, { recursive: true });

const load = (f) => JSON.parse(readFileSync(join(srcDir, f), 'utf8'));
const primitives = load('primitives.tokens.json');
const dark = load('semantic.dark.tokens.json');
const light = load('semantic.light.tokens.json');

/** Walk a DTCG tree → [{ path: [...], type, value }] */
function collect(node, path = [], out = []) {
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      out.push({ path: [...path, key], type: val.$type, value: val.$value });
    } else if (val && typeof val === 'object') {
      collect(val, [...path, key], out);
    }
  }
  return out;
}

/** Resolve {a.b.c} aliases against the primitives tree. */
function resolve(value, seen = new Set()) {
  if (typeof value !== 'string' || !value.startsWith('{')) return value;
  const ref = value.slice(1, -1);
  if (seen.has(ref)) throw new Error(`Circular alias: ${ref}`);
  seen.add(ref);
  let node = primitives;
  for (const part of ref.split('.')) {
    node = node?.[part];
    if (node === undefined) throw new Error(`Unresolvable alias: ${value}`);
  }
  return resolve(node.$value, seen);
}

const kebab = (s) => s.toLowerCase().replace(/[^a-z0-9-]+/g, '-');

/** Token path → CSS var name. Semantic color groups get a color- prefix. */
const SEMANTIC_COLOR_GROUPS = new Set(['text', 'bg', 'stroke', 'icon', 'shadow']);
function cssName(path) {
  const parts = path.map(kebab);
  const prefix = SEMANTIC_COLOR_GROUPS.has(parts[0]) ? 'color-' : '';
  return `--br-${prefix}${parts.join('-')}`;
}

function cssValue(type, value) {
  if (type === 'dimension' && typeof value === 'number') return value === 0 ? '0' : `${value}px`;
  return String(value);
}

const primTokens = collect(primitives);
const darkTokens = collect(dark).map((t) => ({ ...t, value: resolve(t.value) }));
const lightTokens = collect(light).map((t) => ({ ...t, value: resolve(t.value) }));

// Guard: light and dark must define the identical token set.
const names = (ts) => ts.map((t) => cssName(t.path)).sort().join(',');
if (names(darkTokens) !== names(lightTokens)) {
  const d = new Set(darkTokens.map((t) => cssName(t.path)));
  const l = new Set(lightTokens.map((t) => cssName(t.path)));
  const miss = [...d].filter((n) => !l.has(n)).concat([...l].filter((n) => !d.has(n)));
  throw new Error(`Light/dark token sets differ: ${miss.join(', ')}`);
}

const line = (t) => `  ${cssName(t.path)}: ${cssValue(t.type, t.value)};`;

const css = `/* Generated by src/tokens/build.mjs — DO NOT EDIT.
 * Source: src/tokens/source/*.tokens.json (mirrors Figma variables).
 * Dark is the default theme. Opt into light with data-theme="light". */

:root {
  color-scheme: dark;

  /* Primitives — never use directly in components */
${primTokens.map(line).join('\n')}

  /* Semantic — dark (default) */
${darkTokens.map(line).join('\n')}
}

[data-theme='light'] {
  color-scheme: light;

${lightTokens.map(line).join('\n')}
}
`;

writeFileSync(join(distDir, 'tokens.css'), css);

const flat = {};
for (const t of primTokens) flat[cssName(t.path)] = cssValue(t.type, t.value);
const themes = { dark: {}, light: {} };
for (const t of darkTokens) themes.dark[cssName(t.path)] = cssValue(t.type, t.value);
for (const t of lightTokens) themes.light[cssName(t.path)] = cssValue(t.type, t.value);

const js = `// Generated by src/tokens/build.mjs — DO NOT EDIT.
export const primitives = ${JSON.stringify(flat, null, 2)};
export const themes = ${JSON.stringify(themes, null, 2)};
export const breakpoints = { sm: 640, md: 768, lg: 1024, xl: 1280 };
`;
writeFileSync(join(distDir, 'tokens.js'), js);

const dts = `// Generated by src/tokens/build.mjs — DO NOT EDIT.
export declare const primitives: Record<string, string>;
export declare const themes: { dark: Record<string, string>; light: Record<string, string> };
export declare const breakpoints: { sm: number; md: number; lg: number; xl: number };
`;
writeFileSync(join(distDir, 'tokens.d.ts'), dts);

console.log(
  `Built ${primTokens.length} primitives + ${darkTokens.length} semantic tokens × 2 themes → dist/`
);
